name: bearing_env
channels:
  - conda-forge
  - pytorch
  - defaults
  - anaconda
dependencies:
  - python=3.7
  - paramiko=2.4.2
  - tqdm
  - cudatoolkit=10.2
  - tensorflow=1.15
  - pytorch=1.6.0
  - torchvision=0.7.0 
  - ignite
  - scikit-learn
  - matplotlib=3.3.0
  - seaborn=0.10.1
  - pyyaml
  - pip:
      - tensorboardX
      - tensorboard
      - torchsummary
